# example: .github/workflows/bashunit-tests.yml
name: Tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  tests:
    name: "Run tests"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: "Install bashunit"
        run: |
          cd test
          curl -s https://bashunit.typeddevs.com/install.sh > install.sh
          chmod +x install.sh
          ./install.sh

      - name: "Test"
        run: |
          cd test
          ./lib/bashunit
